#!/bin/bash

if [[ $1 == "" || ! -d $1 ]]; then
    echo "error: path to existing blink source folder is required"
    exit 1
fi

type git >/dev/null 2>&1 || { echo >&2 "error: git is required"; exit 1; }
type python >/dev/null 2>&1 || { echo >&2 "error: python is required"; exit 1; }

# Process files
cd $1
git pull
cd - 2 >/dev/null 2>&1 
python "$(dirname "$0")"/process.py $1

# Push updates
cd "$(dirname "$0")"
git add *
git commit -m "Updated files"
git push
